services:
  frontend:
    build: ./frontend
    container_name: maplestory-frontend
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - caddy
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: maplestory-backend
    env_file: .env
    environment:
      - NODE_ENV=production
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - caddy
      - db
      - app
    restart: unless-stopped

networks:
  caddy:
    external: true
  db:
    external: true
  app:
    external: true
